# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "elkserver" do |elkserver|
    elkserver.vm.box = "chef/centos-6.5"
    elkserver.vm.hostname = "elk-server.localdomain"
    elkserver.vm.network "forwarded_port", guest: 22, host: 2201, id: 'ssh'
    elkserver.vm.network "forwarded_port", guest: 8080, host: 8080
    elkserver.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.100', :name => 'vboxnet0', :adapter => 2
    end
    elkserver.vm.provider "virtualbox" do |vb|
      vb.name = "ELK server - Ansible"
      vb.gui = true
      vb.memory = "512"
    end

    elkserver.vm.provision :ansible do |ansible|
      ansible.playbook = "bootstrap_server.yml"
      ansible.inventory_path = "hosts"
      ansible.sudo = true
    end    

  end

  config.vm.define "elkclient" do |elkclient|


    elkclient.vm.box = "chef/centos-6.5"
    elkclient.vm.hostname = "elk-client.localdomain"
    elkclient.vm.network "forwarded_port", guest: 22, host: 2202, id: 'ssh'
    elkclient.vm.provider "virtualbox" do |vb| 
  	config.vm.network "private_network", :ip => '172.28.128.50', :name => 'vboxnet0', :adapter => 2
    end
    elkclient.vm.provider "virtualbox" do |vb|
      vb.name = "ELK client - Ansible"
      vb.gui = true
      vb.memory = "512"
    end
    
    elkclient.vm.provision :ansible do |ansible|
      ansible.playbook = "bootstrap_client.yml"
      ansible.inventory_path = "hosts"
      ansible.sudo = true
    end

  end

end
