# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.username = "root"
  config.ssh.password = "vagrant"

  #Shard deployment

  config.vm.define "shard1" do |shard1|
    shard1.vm.box = "chef/centos-6.5"
    shard1.vm.hostname = "mongo-shard1.localdomain"
    shard1.vm.network "forwarded_port", guest: 22, host: 2203, id: 'ssh'
    shard1.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.30', :name => 'vboxnet0', :adapter => 2
    end
    shard1.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - shard server 1"
      vb.gui = true
      vb.memory = "512"
    end
  end

  config.vm.define "shard2" do |shard2|
    shard2.vm.box = "chef/centos-6.5"
    shard2.vm.hostname = "mongo-shard2.localdomain"
    shard2.vm.network "forwarded_port", guest: 22, host: 2204, id: 'ssh'
    shard2.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.31', :name => 'vboxnet0', :adapter => 2
    end
    shard2.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - shard server 2"
      vb.gui = false
      vb.memory = "512"
    end
  end

  config.vm.define "shard3" do |shard3|
    shard3.vm.box = "chef/centos-6.5"
    shard3.vm.hostname = "mongo-shard3.localdomain"
    shard3.vm.network "forwarded_port", guest: 22, host: 2205, id: 'ssh'
    shard3.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.32', :name => 'vboxnet0', :adapter => 2
    end
    shard3.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - shard server 3"
      vb.gui = false
      vb.memory = "512"
    end
  end

  config.vm.define "shard4" do |shard4|
    shard4.vm.box = "chef/centos-6.5"
    shard4.vm.hostname = "mongo-shard4.localdomain"
    shard4.vm.network "forwarded_port", guest: 22, host: 2206, id: 'ssh'
    shard4.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.32', :name => 'vboxnet0', :adapter => 2
    end
    shard4.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - shard server 4"
      vb.gui = false
      vb.memory = "512"
    end
  end


  #Config server deployment

  config.vm.define "config1" do |config1|
    config1.vm.box = "chef/centos-6.5"
    config1.vm.hostname = "mongo-config1.localdomain"
    config1.vm.network "forwarded_port", guest: 22, host: 2207, id: 'ssh'
    config1.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.10', :name => 'vboxnet0', :adapter => 2
    end
    config1.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - config server 1"
      vb.gui = true
      vb.memory = "512"
    end
  end

  config.vm.define "config2" do |config2|
    config2.vm.box = "chef/centos-6.5"
    config2.vm.hostname = "mongo-config2.localdomain"
    config2.vm.network "forwarded_port", guest: 22, host: 2208, id: 'ssh'
    config2.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.11', :name => 'vboxnet0', :adapter => 2
    end
    config2.vm.provider "virtualbox" do |vb|       
      vb.name = "Mongo - config server 2"
      vb.gui = false
      vb.memory = "512"
    end
  end

  config.vm.define "config3" do |config3|
    config3.vm.box = "chef/centos-6.5"
    config3.vm.hostname = "mongo-config3.localdomain"
    config3.vm.network "forwarded_port", guest: 22, host: 2209, id: 'ssh'
    config3.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.12', :name => 'vboxnet0', :adapter => 2
    end
    config3.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - config server 3"
      vb.gui = false
      vb.memory = "512"
    end
  end

  #Query router deployment

  config.vm.define "query1" do |query1|
    query1.vm.box = "chef/centos-6.5"
    query1.vm.hostname = "mongo-query1.localdomain"
    query1.vm.network "forwarded_port", guest: 22, host: 2210, id: 'ssh'
    query1.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.20', :name => 'vboxnet0', :adapter => 2
    end
    query1.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - query router 1"
      vb.gui = true
      vb.memory = "512"
    end
  end

  config.vm.define "query2" do |query2|
    query2.vm.box = "chef/centos-6.5"
    query2.vm.hostname = "mongo-query2.localdomain"
    query2.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh'
    query2.vm.provider "virtualbox" do |vb|
        config.vm.network "private_network", :ip => '172.28.128.21', :name => 'vboxnet0', :adapter => 2
    end
    query2.vm.provider "virtualbox" do |vb|
      vb.name = "Mongo - query router 2"
      vb.gui = false
      vb.memory = "512"
    end

    query2.vm.provision "file", source: "./addshards.js", destination: "/tmp/addshards.js"

  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.inventory_path = "hosts"
    ansible.sudo = true
  end
end
