---
- name: Make Mongo's data directory
  file: path=/mongo-metadata state=directory mode=0755 owner=mongod group=mongod

- name: Copy config files to correct place
  copy: src=mongod.conf dest=/etc/mongod.conf force=yes

- name: Start up MongoD in the appropriate mode
  service: name=mongod enabled=yes state=started
