---
- name: ensure SELinux bindings are available for dependencies
  yum: pkg=libselinux-python state=present

- name: ensure MongoDB repo is present
  copy: src=mongodb-org-3.0.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo 

- name: update hosts file information
  lineinfile: dest=/etc/hosts regexp="{{ item }}" insertafter="^::1" line="{{ item }}"
  with_items:
  - '172.28.128.10             mongo-config1.localdomain'
  - '172.28.128.11             mongo-config2.localdomain'
  - '172.28.128.12             mongo-config3.localdomain'
  - '172.28.128.20             mongo-query1.localdomain'
  - '172.28.128.21             mongo-query2.localdomain'
  - '172.28.128.30             mongo-data-1-1.localdomain'
  - '172.28.128.31             mongo-data-1-2.localdomain'
  - '172.28.128.32             mongo-data-1-3.localdomain'
  - '172.28.128.33             mongo-data-2-1.localdomain'
  - '172.28.128.34             mongo-data-2-2.localdomain'
  - '172.28.128.35             mongo-data-2-3.localdomain'

- name: install MongoDB stable release (v3)
  yum: pkg=mongodb-org state=present
