apiVersion: v1
kind: Service
metadata:
  name: drupal8-test-service
  labels:
    app: drupal8-test-stack
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: drupal8-test-stack
---
apiVersion: v1
kind: Service
metadata:
  name: drupal8-test-db-service
  labels:
    app: drupal8-mariadb-server
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30002
  selector:
    app: drupal8-mariadb-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drupal8-test-stack
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: drupal8-test-stack
    spec:
      containers:
      - name: apache
        image: appnomatt/apache-test:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
      volumes:
      - name: webroot
        hostPath:
          path: /webdir
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drupal8-mariadb-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal8-mariadb-server
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_USER
          value: "drupaltest"
        - name: MYSQL_PASSWORD
          value: "drupaltest"
        - name: MYSQL_DATABASE
          value: "drupaltest"
